# Generated by Django 2.2.4 on 2019-08-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_skill_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(choices=[(1, 'Just Getting Started'), (2, 'Familiar'), (3, 'Proficient'), (4, 'Professional')], default=1),
            preserve_default=False,
        ),
    ]
