# Generated by Django 2.2.4 on 2019-08-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_skill_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_category',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
