# Generated by Django 2.2.4 on 2019-08-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20190829_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AlterField(
            model_name='skill_category',
            name='proficiency',
            field=models.IntegerField(choices=[(1, 'Just Getting Started'), (2, 'Familiar'), (3, 'Proficient'), (4, 'Professional')]),
        ),
    ]
