# Generated by Django 2.2.4 on 2019-08-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
