# Generated by Django 2.2.4 on 2019-08-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20190830_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
