# Generated by Django 3.1 on 2020-08-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_project_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('picture', models.ImageField(upload_to='experiences/')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('priority', models.IntegerField()),
                ('picture', models.ImageField(upload_to='interests/')),
            ],
        ),
    ]
