# Generated by Django 3.1 on 2020-08-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_experience_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='description',
        ),
    ]
